version: "3.8"

services:
  # Server for REST API and SOCKET.IO
  server-api:
    image: sfcs/server-api:v1.production
    restart: unless-stopped
    volumes:
      - ${DOCKER_IMAGES}:/app/images
    environment:
      - HOST=${HOST}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - PORT=${SERVER_API_PORT}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - IMAGES_DIRECTORY=/app/images
    ports:
      - "${PUBLIC_SERVER_API_PORT}:${SERVER_API_PORT}"
          
  # Client web, images and webserver
  client-web:
    image: sfcs/client-web:v1.production
    restart: unless-stopped
    volumes:
      - ./database/images:/app/images
      - ${DOCKER_IMAGES}:/data/images
    environment:
      - VUE_APP_DOMAIN=${HOST}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    ports:
      - "4430:80"
    depends_on:
      - server-api