version: "3.8"

services:
  # Server for REST API and SOCKET.IO
  server-api:
    image: sfcs/server-api:v1.production
    restart: unless-stopped
    build:
      context: ./server-api
      dockerfile: Dockerfile.prod
    volumes:
      - ${DOCKER_IMAGES}:${IMAGES_DIRECTORY}
    environment:
      - HOST=${HOST}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - PORT=${SERVER_API_PORT}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - IMAGES_DIRECTORY=${IMAGES_DIRECTORY}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
          
  # Client web, images and webserver
  client-web:
    image: sfcs/client-web:v1.production
    restart: unless-stopped
    build:
      context: ./client-web
      dockerfile: Dockerfile.prod
      args:
        - VUE_APP_DOMAIN=${HOST}
        - VUE_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - VUE_APP_GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
    volumes:
      - ${DOCKER_IMAGES}:/data/images
    ports:
      - "4430:80"
    depends_on:
      - server-api