FROM node:14-alpine as build-stage

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

FROM nginx:1.19-alpine as production-stage

COPY --from=build-stage /app/nginx.conf.production /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]