FROM node:14 as build-stage

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

FROM nginx:1.19 as production-stage

WORKDIR /app

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY ./nginx.conf.production /etc/nginx/conf.d/default.conf
COPY ./docker ./docker
RUN chmod 777 ./docker/entrypoint.production.sh

ENTRYPOINT ./docker/entrypoint.production.sh